<?php

return [
    // AI Agent
    'NovaAct',
    'AmazonBuyForMe',
    'GoogleAgent-Mariner',
    // AI Assistant
    'Amzn-User',
    'DuckAssistBot',
    'Meta-ExternalAgent',
    'Google-NotebookLM',
    'Gemini-Deep-Research',
    'GoogleAgent-Search',
    'Google-Pinpoint',
    'ChatGPT-User',
    'ChatGPT-Browser',
    'Claude-User',
    'GitHubCopilotChat',
    'Perplexity-User',
    'Big Sur AI',
    'Ai2Bot-DeepResearchEval',
    'Character-AI',
    'MistralAI-User',
    'Devin',
    'LinerBot',
    'Poggio-Citations',
    'QualifiedBot',
    'Manus-User',
    // AI Data Scraper
    'Applebot-Extended',
    'Google-CloudVertexBot',
    'Google-Extended',
    'webzio-extended',
    'Doximity-Diffbot',
    'Diffbot',
    'GPTBot',
    'ClaudeBot',
    'ImageSift',
    'Anthropic AI',
    'Cohere AI',
    'Cohere-Command',
    'cohere-training-data-crawler',
    'TerraCotta',
    'Replicate-Bot',
    'Together-Bot',
    'xAI-Bot',
    'Groq-Bot',
    'FirecrawlAgent',
    'Ai2Bot-Dolma',
    'Ai2Bot',
    'DeepseekBot',
    'Crawlspace',
    'RunPod-Bot',
    'HuggingFace-Bot',
    'iAskBot',
    'ChatGLM-Spider',
    'Sider',
    'SBIntuitionsBot',
    'IAS Crawler',
    'IAS Wombles',
    'ShapBot',
    'PanguBot',
    // AI Search Crawler
    'Amazonbot',
    'Amzn-SearchBot',
    'Applebot',
    'Bard-AI',
    'Gemini-AI',
    'webzio',
    'YandexAdditionalBot',
    'OAI-SearchBot',
    'Claude-SearchBot',
    'Claude-Web',
    'YouBot',
    'PerplexityBot',
    'IbouBot',
    'Andibot',
    'ZanistaBot',
    'ProRata',
];
